name: book_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  linked_scroll_controller: ^0.2.0
  translator: ^0.1.7
  shared_preferences: ^2.1.0
  google_fonts: ^4.0.3
  multiselect: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

assets:
  - assets/
